// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayIn.Api.Data;

#nullable disable

namespace StayinApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106094026_AddSeedListingsFixed")]
    partial class AddSeedListingsFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StayIn.Api.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressBuilding")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressDistrict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Beds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Guests")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "A Blok Kat:3",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Çeşme",
                            AddressPostalCode = "35930",
                            AddressRegion = "Ege",
                            AddressStreet = "Alaçatı Mahallesi, Sahil Caddesi No:45",
                            Amenities = "[\"Wifi\",\"Klima\",\"Havuz\",\"Jakuzi\",\"Deniz Manzaras\\u0131\",\"\\u00D6zel Plaj\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çeşme'nin en güzel sahilinde, deniz manzaralı modern daire. Havuz, jakuzi ve özel plaj erişimi mevcut.",
                            Guests = 4,
                            Latitude = 38.322800000000001,
                            Longitude = 26.302499999999998,
                            PhotoUrls = "[]",
                            PlaceType = "Daire",
                            Price = 2500m,
                            Title = "Deniz Manzaralı Lüks Daire"
                        },
                        new
                        {
                            Id = 2,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kalkan",
                            AddressPostalCode = "07960",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Kalamar Mahallesi, Yalı Sokak No:12",
                            Amenities = "[\"Wifi\",\"Klima\",\"Havuz\",\"Bah\\u00E7e\",\"Mangal\",\"Deniz Manzaras\\u0131\",\"\\u00D6zel Otopark\"]",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            Beds = 5,
                            CreatedAt = new DateTime(2024, 11, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Kalkan'da özel havuzlu, geniş bahçeli lüks villa. Muhteşem deniz manzarası ve sessiz konum.",
                            Guests = 8,
                            Latitude = 36.265599999999999,
                            Longitude = 29.408899999999999,
                            PhotoUrls = "[]",
                            PlaceType = "Villa",
                            Price = 5000m,
                            Title = "Modern Villa Havuz ve Bahçe"
                        },
                        new
                        {
                            Id = 3,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Butik Otel",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Bodrum",
                            AddressPostalCode = "48400",
                            AddressRegion = "Ege",
                            AddressStreet = "Gümbet Mahallesi, Plaj Yolu No:8",
                            Amenities = "[\"Wifi\",\"Klima\",\"TV\",\"Kahvalt\\u0131\",\"Plaja Yak\\u0131n\",\"Restoran\"]",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Bodrum'un kalbinde, plaja yürüme mesafesinde modern ve konforlu konaklama. Kahvaltı dahil.",
                            Guests = 6,
                            Latitude = 37.034399999999998,
                            Longitude = 27.430499999999999,
                            PhotoUrls = "[]",
                            PlaceType = "Ev",
                            Price = 3200m,
                            Title = "Plaja Sıfır Butik Otel"
                        },
                        new
                        {
                            Id = 4,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Bungalov 5",
                            AddressCity = "Bolu",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Abant",
                            AddressPostalCode = "14100",
                            AddressRegion = "Karadeniz",
                            AddressStreet = "Göl Mahallesi, Doğa Yolu No:23",
                            Amenities = "[\"Wifi\",\"\\u015E\\u00F6mine\",\"Veranda\",\"G\\u00F6l Manzaras\\u0131\",\"Do\\u011Fa\",\"Mangal\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 5, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Abant Gölü manzaralı, doğa ile iç içe huzurlu bungalov. Şömine, veranda ve orman manzarası.",
                            Guests = 3,
                            Latitude = 40.616700000000002,
                            Longitude = 31.2667,
                            PhotoUrls = "[]",
                            PlaceType = "Kulübe",
                            Price = 1800m,
                            Title = "Doğa İçinde Bungalov"
                        });
                });

            modelBuilder.Entity("StayIn.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationCodeExpires")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
